### ISSUE TITLE
Reloadbot not working

### ISSUE THREAD

**Issue by Bram1903** [Tomato6966/discord-js-v13-handler#2]
Hello,

Something goes wrong while trying to reload the bot. It seems like there is something wrong with posting it too the API

Could you look at this?

Regards,
Bram

**Comment by Toskan4134** [comment]
Look at my pull request

**Comment by MayiVT** [comment]
> Look at my pull request

TypeError: Cannot read properties of undefined (reading 'size')
    at Object.run (/var/ftp/Mayi/projects/NekoWaterv3/commands/Owner/reloadbot.js:45:149)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Toskan4134** [comment]
> > Look at my pull request
> 
> TypeError: Cannot read properties of undefined (reading 'size') at Object.run (/var/ftp/Mayi/projects/NekoWaterv3/commands/Owner/reloadbot.js:45:149) at processTicksAndRejections (node:internal/process/task_queues:96:5)

Try it now, i changed some things that i left.

**Comment by MayiVT** [comment]
> Try it now, i changed some things tha

TypeError: Cannot read properties of undefined (reading 'set')
    at module.exports (/var/ftp/Mayi/projects/NekoWaterv3/handlers/handlers.js:11:29)
    at /var/ftp/Mayi/projects/NekoWaterv3/index.js:54:37
    at Array.forEach (<anonymous>)
    at handlers (/var/ftp/Mayi/projects/NekoWaterv3/index.js:53:8)
    at Object.<anonymous> (/var/ftp/Mayi/projects/NekoWaterv3/index.js:57:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
